export enum AppErrorType {
  CLIENT_ERROR = "CLIENT_ERROR",
  INTERNAL_ERROR = "INTERNAL_ERROR",
  CONFLICT_ERROR = "CONFLICT_ERROR",
  CONFIGURATION_ERROR = "CONFIGURATION_ERROR",
  ARGUMENT_ERROR = "ARGUMENT_ERROR",
  CONNECTIVITY_ERROR = "CONNECTIVITY_ERROR",
  AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR",
  AUTHORIZATION_ERROR = "AUTHORIZATION_ERROR",
  VALIDATION_ERROR = "VALIDATION_ERROR",
}
